import { getGitHubConfig, getToken } from './github-sync.js';

const STATE_KEY='trading-os-state-v1';
const PENDING_KEY='trading-os-pending-v1';
const DATE_FILTER_KEY='trading-os-trade-log-date-filter';
const DB_NAME='trading-os-trade-docs-v1';
const STORE='blobs';
let dbPromise=null,scanTimer=null;

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#39;"}[c]));
const nowIso=()=>new Date().toISOString();
const loadState=()=>{try{return JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}catch{return{trades:[]}}};
function saveState(s){s.meta=s.meta||{};s.meta.updatedAt=nowIso();localStorage.setItem(STATE_KEY,JSON.stringify(s));localStorage.setItem(PENDING_KEY,'1');window.dispatchEvent(new CustomEvent('trading-os-documentation-change',{detail:{updatedAt:s.meta.updatedAt}}));}
function docOf(t){const d=t?.documentation||{};return{charts:d.charts||{entry:null,exit:null},importantNotes:Array.isArray(d.importantNotes)?d.importantNotes:[],chartAddenda:Array.isArray(d.chartAddenda)?d.chartAddenda:[],reviewAddenda:Array.isArray(d.reviewAddenda)?d.reviewAddenda:[],reviewSnapshot:d.reviewSnapshot||null,reviewFinalizedAt:d.reviewFinalizedAt||null};}
const adherence=x=>x==='Yes'?'ملتزم بالخطة':x==='Partially'?'ملتزم جزئيًا':x==='No'?'غير ملتزم بالخطة':(x||'—');
const nyDate=iso=>{try{return new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso))+' NY'}catch{return iso||'—'}};

function db(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbPromise;}
async function getBlob(key){if(!key)return null;const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE,'readonly').objectStore(STORE).get(key);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
function apiHeaders(token){return{'Accept':'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'}}
async function fetchRemoteBlob(path){const token=getToken(),cfg=getGitHubConfig();if(!token||!path)return null;const url=`https://api.github.com/repos/${encodeURIComponent(cfg.owner)}/${encodeURIComponent(cfg.repo)}/contents/${path}?ref=${encodeURIComponent(cfg.branch||'main')}`;const r=await fetch(url,{headers:apiHeaders(token)});if(!r.ok)return null;const x=await r.json(),bin=atob(String(x.content||'').replace(/\n/g,'')),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new Blob([bytes],{type:'image/webp'});}
async function blobFor(rec){return(await getBlob(rec?.localKey).catch(()=>null))||(rec?.path?await fetchRemoteBlob(rec.path).catch(()=>null):null)}

function reviewValue(r,...keys){for(const k of keys){const v=r?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return'—'}
function bridgeHtml(t){
  const d=docOf(t),review=d.reviewSnapshot||t.review||{},notes=[...d.importantNotes].sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt)),adds=[...d.reviewAddenda].sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt));
  const chart=(key,title)=>{const rec=d.charts[key];return`<div class="trade-bridge-chart"><div class="trade-bridge-chart-head"><b>${title}</b>${rec?'<span>Original · مقفل</span>':'<span class="missing">مفقود</span>'}</div><div class="trade-bridge-img" ${rec?`data-bridge-img="${esc(rec.id)}"`:''}>${rec?'جاري تحميل الصورة…':'لا توجد صورة أصلية.'}</div></div>`};
  return `<section class="trade-log-docs-bridge" data-trade-docs-id="${esc(t.id)}"><div class="trade-bridge-title"><div><h3>الشارتات والمراجعة</h3><p>التوثيق المرتبط بهذه الصفقة</p></div>${d.reviewFinalizedAt?`<span class="locked">المراجعة الأصلية مقفلة · ${esc(nyDate(d.reviewFinalizedAt))}</span>`:''}</div><div class="trade-bridge-charts">${chart('entry','شارت الدخول')}${chart('exit','شارت الإغلاق')}</div>${notes.length?`<div class="trade-bridge-important"><h4>⚠ معلومة مهمة</h4>${notes.map(n=>`<div class="trade-bridge-note"><time>${esc(nyDate(n.createdAt))}</time><p>${esc(n.text)}</p></div>`).join('')}</div>`:''}<div class="trade-bridge-review"><h4>مراجعة الصفقة</h4><div class="trade-bridge-review-grid"><div><small>الالتزام بالخطة</small><b>${esc(adherence(review.adherence))}</b></div><div><small>الخطأ الرئيسي</small><b>${esc(reviewValue(review,'error','mistake','errorType','mainError'))}</b></div><div><small>الدرس المستفاد</small><b>${esc(reviewValue(review,'lesson','lessons','takeaway'))}</b></div></div>${adds.length?`<div class="trade-bridge-addenda"><h5>مراجعات لاحقة</h5>${adds.map(a=>`<div><time>${esc(nyDate(a.createdAt))}</time><p>${esc(a.text)}</p></div>`).join('')}</div>`:''}</div></section>`;
}
async function hydrateBridge(root,t){const d=docOf(t),records=[d.charts.entry,d.charts.exit].filter(Boolean);for(const rec of records){const wrap=root.querySelector(`[data-bridge-img="${CSS.escape(rec.id)}"]`);if(!wrap)continue;const blob=await blobFor(rec);if(!blob){wrap.textContent='تعذر تحميل الصورة على هذا الجهاز. تأكد من ربط GitHub.';continue}const img=document.createElement('img');img.src=URL.createObjectURL(blob);wrap.innerHTML='';wrap.appendChild(img)}}
function modalCandidates(){const set=new Set();document.querySelectorAll('#modal-root > *,#modal-root .modal,#modal-root [role="dialog"],.modal[role="dialog"],.modal').forEach(x=>set.add(x));return[...set].filter(x=>!x.closest('.doc-overlay')&&x.offsetParent!==null)}
function injectIntoTradeDetails(){const state=loadState();for(const modal of modalCandidates()){const id=(modal.textContent||'').match(/TR-[A-Za-z0-9-]+/)?.[0];if(!id)continue;const t=(state.trades||[]).find(x=>x.id===id);if(!t)continue;const old=modal.querySelector('.trade-log-docs-bridge');if(old?.dataset.tradeDocsId===id)continue;old?.remove();const host=modal.querySelector('.modal-body,.dialog-body,.content')||modal;const temp=document.createElement('div');temp.innerHTML=bridgeHtml(t);const section=temp.firstElementChild;host.appendChild(section);hydrateBridge(section,t)}}

function wallToIso(value,zone){if(!value)return null;const [d,tm]=value.split('T'),[Y,M,D]=d.split('-').map(Number),[h,m]=tm.split(':').map(Number);if(zone==='KSA')return new Date(Date.UTC(Y,M-1,D,h-3,m,0)).toISOString();let guess=Date.UTC(Y,M-1,D,h,m,0);for(let i=0;i<4;i++){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date(guess)).map(x=>[x.type,x.value]));const shown=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,0),wanted=Date.UTC(Y,M-1,D,h,m,0);guess+=wanted-shown}return new Date(guess).toISOString()}
function dateInZone(iso,zone){try{const tz=zone==='KSA'?'Asia/Riyadh':'America/New_York',p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(iso)).map(x=>[x.type,x.value]));return`${p.year}-${p.month}-${p.day}`}catch{return new Date(iso).toISOString().slice(0,10)}}
function injectEntryTime(){document.querySelectorAll('.trade-doc-requirement[data-doc-phase="ENTRY"]').forEach(box=>{if(box.querySelector('.trade-entry-time-block'))return;const block=document.createElement('div');block.className='trade-entry-time-block';block.innerHTML=`<div class="trade-entry-time-title"><b>تاريخ ووقت الدخول الفعلي</b><span>اختياري</span></div><div class="trade-entry-time-grid"><label><small>التاريخ والوقت</small><input type="datetime-local" data-entry-wall-time></label><label><small>التوقيت</small><select data-entry-time-zone><option value="NY">نيويورك (NY)</option><option value="KSA">السعودية</option></select></label></div><p>إذا تركت التاريخ والوقت فارغًا، يستخدم النظام وقت الضغط على بدء الصفقة تلقائيًا. وقت إنشاء السجل يبقى منفصلًا عن وقت التنفيذ.</p>`;const important=box.querySelector('.trade-doc-important');important?box.insertBefore(block,important):box.appendChild(block)})}
function startMatch(btn){const t=(btn?.textContent||'').trim().replace(/\s+/g,' ');return /^(START TRADE|بدء الصفقة|ابدأ الصفقة|فتح الصفقة)$/i.test(t)}
async function waitNewTrade(before){for(let i=0;i<55;i++){await new Promise(r=>setTimeout(r,90));const s=loadState(),t=(s.trades||[]).filter(x=>!before.has(x.id)).sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0))[0];if(t)return t}return null}
async function recordEntryTime(before,iso,source,zone,manualDate){const found=await waitNewTrade(before);if(!found)return;await new Promise(r=>setTimeout(r,350));const s=loadState(),t=(s.trades||[]).find(x=>x.id===found.id);if(!t)return;t.actualEntryAt=iso;t.entryTimeSource=source;t.date=manualDate||dateInZone(iso,zone);const ev=(t.events||[]).find(e=>e.type==='INITIAL');if(ev){ev.actualTimestamp=iso;ev.timeSource=source==='AUTO_NOW'?'EXECUTION_AUTO':source}saveState(s)}
document.addEventListener('click',e=>{const btn=e.target.closest('button');if(!startMatch(btn))return;const box=btn.closest('.modal,.page,form')?.querySelector('.trade-doc-requirement[data-doc-phase="ENTRY"]')||document.querySelector('.trade-doc-requirement[data-doc-phase="ENTRY"]');if(!box||!box.classList.contains('doc-ready'))return;const input=box.querySelector('[data-entry-wall-time]'),zone=box.querySelector('[data-entry-time-zone]')?.value||'NY',manual=input?.value||'',clicked=nowIso(),iso=manual?wallToIso(manual,zone):clicked,source=manual?(zone==='KSA'?'MANUAL_KSA':'MANUAL_NY'):'AUTO_NOW',before=new Set((loadState().trades||[]).map(x=>x.id));recordEntryTime(before,iso,source,zone,manual?manual.slice(0,10):null)},true);

function currentDateFilter(){return localStorage.getItem(DATE_FILTER_KEY)||''}
function clearDateFilter(){localStorage.removeItem(DATE_FILTER_KEY);document.querySelectorAll('.trade-day-filter-banner').forEach(x=>x.remove());document.querySelectorAll('tr[data-trade-date-hidden="1"]').forEach(x=>{x.hidden=false;delete x.dataset.tradeDateHidden})}
function applyTradeDateFilter(){const date=currentDateFilter();if(!date)return;const state=loadState(),byId=new Map((state.trades||[]).map(t=>[t.id,t]));let matchedTable=null,count=0;document.querySelectorAll('table').forEach(table=>{const rows=[...table.querySelectorAll('tbody tr')],tradeRows=rows.map(row=>({row,id:(row.textContent||'').match(/TR-[A-Za-z0-9-]+/)?.[0]})).filter(x=>x.id&&byId.has(x.id));if(!tradeRows.length)return;matchedTable=table;for(const x of tradeRows){const show=byId.get(x.id)?.date===date;x.row.hidden=!show;if(!show)x.row.dataset.tradeDateHidden='1';else{delete x.row.dataset.tradeDateHidden;count++}}});if(!matchedTable)return;let banner=matchedTable.parentElement?.querySelector(':scope > .trade-day-filter-banner');if(!banner){banner=document.createElement('div');banner.className='trade-day-filter-banner';matchedTable.parentElement?.insertBefore(banner,matchedTable)}banner.innerHTML=`<div><b>سجل صفقات ${esc(date)}</b><span>${count} ${count===1?'صفقة':'صفقات'}</span></div><button type="button">عرض كل الأيام</button>`;banner.querySelector('button').onclick=clearDateFilter}
window.addEventListener('trading-os-open-trade-date',e=>{if(e.detail?.date)localStorage.setItem(DATE_FILTER_KEY,e.detail.date);schedule()});

function schedule(){clearTimeout(scanTimer);scanTimer=setTimeout(()=>{injectEntryTime();injectIntoTradeDetails();applyTradeDateFilter()},80)}
window.addEventListener('load',schedule);window.addEventListener('hashchange',schedule);window.addEventListener('focus',schedule);new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});schedule();
